export const ADD_ACTION_RESPONSE = "ADD_ACTION_RESPONSE";

export const GET_ACTIONS_RESPONSE = "GET_ACTIONS_RESPONSE";

export const SET_SELECTED_ACTION = "SET_SELECTED_ACTION";

export const DELETE_ACTION_RESPONSE = "DELETE_ACTION_RESPONSE";