export const GENERATE_DID_RESPONSE = "GENERATE_DID_RESPONSE";
export const CLEAR_KEY_PAIR = "CLEAR_KEY_PAIR";
export const GET_DID_LIST = "GET_DID_LIST";
export const RESOLVE_DID = "RESOLVE_DID";
export const CLEAR_RESOLVED_DID = "CLEAR_RESOLVED_DID";
export const GET_SINGLE_DID = "GET_SINGLE_DID";
export const DELETE_DID = "DELETE_DID";

export const CHANGE_DID_SELECTED_TAB = "CHANGE_DID_SELECTED_TAB";