export const ADD_PROJECT_RESPONSE = "ADD_PROJECT_RESPONSE";

export const GET_PROJECTS_RESPONSE = "GET_PROJECTS_RESPONSE";

export const GET_PROJECT_RESPONSE = "GET_PROJECT_RESPONSE";

export const DELETE_PROJECT_RESPONSE = "DELETE_PROJECT_RESPONSE";

export const CLONE_PROJECT_RESPONSE = "CLONE_PROJECT_RESPONSE";

export const UPDATE_PROJECT_RESPONSE = "UPDATE_PROJECT_RESPONSE";